name: digital_index

channels:
  - conda-forge

dependencies:
  - flake8 >= 3.8.3
  - isort >= 4.3.21
  - jupyterlab
  - matplotlib >= 3.2.2
  - multiprocess >= 0.70.9
  - nltk >= 3.4.4
  - pandas >= 1.0.5
  - pip >= 20.1.1
  - python >= 3.8.3
  - scikit-learn >= 0.23.1
  - seaborn >= 0.10.1
  - sqlalchemy >= 1.3.7
  - sqlite >= 3.30.1
  - pip:
    - googlemaps >= 4.4.1
    - pgeocode
    - pytrends >= 4.7.3
    - uszipcode >= 0.2.4
    - dm-tree >= 0.1.5
    - cloudpickle >= 1.6.0 
    - decorator >= 4.4.2 
    - gast >= 0.4.0 
    - tensorflow-probability >= 0.11.1
    - pmdarima==1.7.1